'use client'
import { useState, useEffect, useRef, use } from 'react'
import { supabase } from '../../../lib/supabase'

const freeQuestions: Record<string, any[]> = {
  'Human Factors': [
    { question: 'According to CASA CHUF syllabus, which part of the eye is responsible for colour vision and fine detail in daylight?', options: ['A. Rods located in the peripheral retina', 'B. Cones concentrated in the fovea centralis', 'C. The optic nerve at the macula', 'D. The iris and ciliary muscle'], correct: 1, explanation: 'Cones are concentrated in the fovea centralis and are responsible for colour vision and high-resolution detail in good lighting. Rods are used for peripheral and night vision.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'A pilot experiences a visual illusion on approach where the runway appears narrower than normal. What is the likely result?', options: ['A. Pilot flies a higher approach than normal', 'B. Pilot flies a lower approach than normal', 'C. No effect on approach path', 'D. Pilot increases airspeed'], correct: 0, explanation: 'A narrower-than-usual runway creates the illusion that the aircraft is higher than it actually is, causing the pilot to fly a dangerously low approach. A narrow runway illusion causes the pilot to fly high.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'What is the definition of Threat and Error Management (TEM) in aviation?', options: ['A. A system for managing ATC threats and crew errors through checklists', 'B. A conceptual framework describing how crews manage threats, errors they make, and undesired aircraft states', 'C. A method of reporting errors to CASA after incidents', 'D. A cockpit procedure for managing automation errors only'], correct: 1, explanation: 'TEM is an ICAO framework that describes how flight crews manage: threats (factors beyond crew control), errors, and undesired aircraft states that result from threats and errors.', reference: 'CASA CHUF Syllabus / ICAO Doc 9683' },
    { question: 'Which of the following best describes physiological stress in aviation?', options: ['A. Psychological pressure from workload only', 'B. Physical stressors including hypoxia, vibration, noise, temperature extremes, and fatigue that degrade performance', 'C. Stress caused only by poor weather conditions', 'D. The emotional response to an emergency'], correct: 1, explanation: 'Physiological stress includes physical stressors such as hypoxia, noise, vibration, temperature, and fatigue that directly degrade cognitive and physical performance.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'What is the function of the semicircular canals in the inner ear?', options: ['A. They detect linear acceleration and gravity', 'B. They detect angular acceleration and rotational motion in three planes', 'C. They control balance only when standing still', 'D. They detect sound vibrations for hearing'], correct: 1, explanation: 'The three semicircular canals detect angular acceleration (rotation) in three planes. They can be deceived in IMC, leading to spatial disorientation.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'What does IMSAFE stand for?', options: ['A. Instruments, Maps, Systems, Airworthiness, Fuel, Emergency', 'B. Illness, Medication, Stress, Alcohol, Fatigue, Emotion', 'C. IFR, Meteorology, Systems, Alternates, Fuel, Equipment', 'D. Inspection, Maintenance, Safety, Airspace, Fuel, Experience'], correct: 1, explanation: 'IMSAFE is a personal minimums checklist: Illness, Medication, Stress, Alcohol, Fatigue, Emotion. Used before flight to assess whether the pilot is fit to fly.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'What is the dark adaptation time required for full night vision?', options: ['A. 5 minutes', 'B. 10 minutes', 'C. 30 minutes', 'D. 45 minutes'], correct: 2, explanation: 'Full dark adaptation takes approximately 30 minutes. Rods (responsible for night vision) are much slower to adapt than cones.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'Which of the following describes the leans spatial disorientation illusion?', options: ['A. A sensation of rolling when the aircraft is in a coordinated turn', 'B. A false sensation that the aircraft is banked when it is actually wings level, causing the pilot to lean in the cockpit', 'C. A sensation of nose-up attitude after rapid acceleration', 'D. A tumbling sensation caused by head movement in a turn'], correct: 1, explanation: 'The leans occur when the pilot returns to wings level after a gradual undetected roll. The semicircular canals still sense the original bank, causing a false sensation of banking.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'What is the primary physiological effect of carbon monoxide poisoning on a pilot?', options: ['A. It increases oxygen carrying capacity of haemoglobin', 'B. It binds to haemoglobin with greater affinity than oxygen, reducing oxygen delivery to tissues and causing hypoxia symptoms', 'C. It causes immediate loss of consciousness', 'D. It primarily affects the vestibular system'], correct: 1, explanation: 'Carbon monoxide binds to haemoglobin with approximately 250 times the affinity of oxygen. Symptoms are similar to hypoxia — headache, dizziness, impaired judgement.', reference: 'CASA CHUF Syllabus / Human Factors Study Guide' },
    { question: 'What is the primary cause of get-there-itis (plan continuation bias)?', options: ['A. Overconfidence in aircraft systems', 'B. The tendency to continue an original plan despite changing conditions, driven by goal fixation', 'C. Lack of instrument training in VMC pilots', 'D. Excessive reliance on GPS navigation'], correct: 1, explanation: 'Get-there-itis is driven by goal fixation — the strong desire to complete the intended flight overrides sound judgement when conditions deteriorate. It is a leading cause of VFR into IMC accidents in Australia.', reference: 'CASA CHUF Syllabus / ATSB Safety Research' },
  ],
  'Aerodynamics': [
    { question: 'What is the function of a vortex generator on a wing?', options: ['A. To increase induced drag at high angles of attack', 'B. To re-energise the boundary layer by mixing fast-moving air from above, delaying flow separation and stall', 'C. To reduce parasite drag in cruise', 'D. To create additional lift at low speeds'], correct: 1, explanation: 'Vortex generators create small vortices which mix high-energy air with the slower boundary layer air. This delays flow separation and improves low-speed handling. A common weak area in CADA.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'What is the effect of a spoiler deployed in flight?', options: ['A. It increases lift and decreases drag', 'B. It disrupts airflow over the wing, simultaneously reducing lift and increasing drag', 'C. It increases the camber of the wing to generate more lift', 'D. It only affects drag with no effect on lift'], correct: 1, explanation: 'Spoilers disrupt smooth airflow over the wing, reducing lift and increasing drag. They are used asymmetrically for roll control and symmetrically as speed brakes.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'What is ground effect and how does it affect aircraft performance on takeoff?', options: ['A. Ground effect increases induced drag, requiring more power near the ground', 'B. Ground effect reduces induced drag by up to 50% when within one wingspan of the ground, allowing the aircraft to fly at lower speeds than it can sustain out of ground effect', 'C. Ground effect has no significant impact on takeoff performance', 'D. Ground effect increases stall speed near the ground'], correct: 1, explanation: 'Ground effect occurs within approximately one wingspan of the ground. The ground interrupts wingtip vortex formation, reducing induced drag by up to 50%. An aircraft can fly in ground effect at speeds below its out-of-ground-effect stall speed.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'What is the effect of wing washout (geometric twist)?', options: ['A. It increases the angle of incidence at the wingtip to improve high-speed performance', 'B. It reduces the angle of incidence progressively toward the wingtip so the root stalls before the tip, maintaining aileron effectiveness at the stall', 'C. It creates a dihedral effect to improve lateral stability', 'D. It reduces wing area to decrease parasite drag'], correct: 1, explanation: 'Washout ensures the wing root reaches the critical angle of attack before the wingtip, maintaining aileron effectiveness throughout the stall.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'How does anhedral affect aircraft lateral stability?', options: ['A. Anhedral increases lateral stability by raising the wingtips', 'B. Anhedral reduces lateral stability — it is used on aircraft that would otherwise be excessively stable laterally', 'C. Anhedral has no effect on lateral stability', 'D. Anhedral increases roll rate at all speeds'], correct: 1, explanation: 'Anhedral (wings angled downward) reduces the natural dihedral effect. It is commonly used on swept-wing and high-wing aircraft which already have strong dihedral effect.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'An aircraft has a stall speed of 60 knots in level flight. What is the stall speed in a 60 degree banked level turn?', options: ['A. 60 knots', 'B. 72 knots', 'C. 85 knots', 'D. 90 knots'], correct: 2, explanation: 'At 60 degrees bank, load factor = 1/cos(60) = 2G. New stall speed = 60 x √2 = 60 x 1.414 = 84.8 knots ≈ 85 knots.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'At what airspeed is best range achieved for a piston-engine aircraft?', options: ['A. At the airspeed where drag is minimum (Vmd) giving maximum lift-to-drag ratio', 'B. At the airspeed where power required is minimum', 'C. At cruise power settings as published in the POH', 'D. At Vy (best rate of climb speed)'], correct: 0, explanation: 'Best range for a piston aircraft is achieved at Vmd (minimum drag) which gives maximum lift-to-drag ratio. At this speed the least fuel is burned per nautical mile.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'What is the best endurance speed for a piston-engine aircraft?', options: ['A. The same as best range speed', 'B. The speed at which power required is minimum (Vmp) — slower than best range speed', 'C. The speed at which maximum lift-to-drag ratio is achieved', 'D. The speed at which fuel flow is minimum regardless of airspeed'], correct: 1, explanation: 'Best endurance for a piston aircraft is at Vmp (minimum power required). At this speed the engine burns the least fuel per hour, maximising time aloft. Vmp is slower than Vmd (best range speed).', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'What is the relationship between aspect ratio and induced drag?', options: ['A. Higher aspect ratio increases induced drag', 'B. Higher aspect ratio decreases induced drag by reducing wingtip vortex strength', 'C. Aspect ratio affects only parasite drag', 'D. Lower aspect ratio decreases induced drag'], correct: 1, explanation: 'Higher aspect ratio (longer, narrower wings) reduces induced drag because the wingtip vortices are proportionally smaller relative to the wing area.', reference: 'CASA CADA Syllabus / Aerodynamics Study Guide' },
    { question: 'What is the significance of the manoeuvring speed (Va)?', options: ['A. The maximum speed at which full flap extension is permitted', 'B. The maximum speed at which full and abrupt control deflection can be applied without exceeding the structural limit load factor', 'C. The speed at which the aircraft achieves best climb performance', 'D. The maximum speed for flight in turbulent conditions'], correct: 1, explanation: 'Below Va, the aircraft will stall before exceeding the limit load factor if full abrupt control input is applied. Above Va, structural damage can result from full control deflection. Va decreases as weight decreases.', reference: 'CASA CADA Syllabus / Aircraft Flight Manual' },
  ],
  'Meteorology': [
    { question: 'What is the stability implication when the environmental lapse rate exceeds the Dry Adiabatic Lapse Rate (DALR)?', options: ['A. The atmosphere is stable', 'B. The atmosphere is absolutely unstable — a displaced parcel accelerates away from its original level, leading to vigorous convection and cumuliform cloud development', 'C. The atmosphere is conditionally unstable', 'D. The atmosphere is in neutral equilibrium'], correct: 1, explanation: 'When the ELR exceeds the DALR, the atmosphere is absolutely unstable. A displaced air parcel becomes warmer than its surroundings and continues to rise, leading to vigorous convection and CB development.', reference: 'CASA CMET Syllabus / Meteorology Study Guide' },
    { question: 'What conditions are necessary for the formation of radiation fog?', options: ['A. Strong winds, high humidity, and frontal passage', 'B. Clear skies, light winds (2-5 knots), high relative humidity, and a long night — typically in valleys', 'C. Onshore winds bringing moist maritime air over cold land', 'D. Orographic lifting of moist air over elevated terrain'], correct: 1, explanation: 'Radiation fog requires: clear skies, light winds, high relative humidity, and a long night for significant cooling. It forms in valleys as cold dense air drains downhill.', reference: 'CASA CMET Syllabus / Meteorology Study Guide' },
    { question: 'What is a microburst and what makes it particularly dangerous to aircraft on approach?', options: ['A. A large-scale downdraft associated with tropical cyclones', 'B. A concentrated downdraft creating a diverging outflow — an aircraft on approach experiences a headwind increase then a downdraft then a tailwind, causing a dangerous loss of energy', 'C. A localised windshift associated with sea breezes', 'D. Severe clear air turbulence near jet streams'], correct: 1, explanation: 'A microburst creates a wind shear pattern: headwind increase (pilot may reduce power), then a downdraft, then a tailwind (airspeed drops dramatically). The total energy loss can be catastrophic at low altitude.', reference: 'CASA CMET Syllabus / Meteorology Study Guide' },
    { question: 'The surface temperature is 26 degrees C and the dewpoint is 10 degrees C. What is the approximate cloud base?', options: ['A. 2400 ft AGL', 'B. 4800 ft AGL', 'C. 6400 ft AGL', 'D. 3200 ft AGL'], correct: 2, explanation: 'Cloud base formula: (Temp - Dewpoint) / 2.5 x 1000 ft = (26-10) / 2.5 x 1000 = 16/2.5 x 1000 = 6.4 x 1000 = 6400 ft AGL.', reference: 'CASA CMET Syllabus / Meteorology Study Guide' },
    { question: 'What causes wind shear associated with a temperature inversion and why is it dangerous on approach?', options: ['A. Turbulence from mountain waves at high altitude', 'B. A sharp change in wind speed and direction over a short distance — causes sudden changes in airspeed and lift, potentially leading to undershoot', 'C. Thermal activity heating the surface layer', 'D. Frontal passage causing backing winds'], correct: 1, explanation: 'Wind shear near the surface (often associated with temperature inversions) causes sudden changes in headwind/tailwind on approach. A sudden headwind loss reduces airspeed and lift, potentially causing an undershoot.', reference: 'CASA CMET Syllabus / Meteorology Study Guide' },
    { question: 'When decoding a METAR that shows BKN025CB, what does the CB suffix indicate?', options: ['A. Cloud base is 25000 ft', 'B. Cumulonimbus cloud — the most significant cloud type associated with severe weather', 'C. Cumulus broken at 2500 ft', 'D. Cloud base is below 2500 ft'], correct: 1, explanation: 'The CB suffix after a cloud group indicates cumulonimbus — the most severe cloud type. BKN025CB = broken cumulonimbus at 2500 ft AAL. The CB suffix must always be noted as it indicates severe weather potential.', reference: 'CASA CMET Syllabus / AIP GEN 3.5' },
    { question: 'What is the difference between a warm front and a cold front in terms of slope and associated weather?', options: ['A. Warm fronts are steeper and faster with showery precipitation', 'B. Warm fronts have a gentle slope (1:150) producing prolonged stratiform rain ahead; cold fronts are steeper (1:50) producing narrow bands of convective weather', 'C. Both fronts produce the same weather', 'D. Cold fronts produce only fog; warm fronts produce only thunderstorms'], correct: 1, explanation: 'Warm fronts have gentle slopes and produce widespread stratiform cloud and prolonged rain well ahead. Cold fronts are steeper, advance faster, and produce narrow but intense convective weather near the surface front.', reference: 'CASA CMET Syllabus / Meteorology Study Guide' },
    { question: 'What is density altitude and how does it affect aircraft performance?', options: ['A. The altitude shown on the altimeter', 'B. Pressure altitude corrected for non-standard temperature — high density altitude reduces engine power, propeller efficiency, and aerodynamic lift', 'C. The altitude at which the aircraft is most fuel efficient', 'D. Height above MSL corrected for terrain'], correct: 1, explanation: 'High density altitude (high elevation, high temperature, high humidity) means less dense air — reduced engine power, reduced propeller thrust, and reduced aerodynamic lift. Critical for performance calculations on hot days.', reference: 'CASA CMET Syllabus / Performance Study Guide' },
    { question: 'What is a Graphical Area Forecast (GAF) and what information does it provide?', options: ['A. A point forecast for major aerodromes', 'B. A graphical depiction of forecast weather areas covering cloud, visibility, significant weather, icing, and turbulence for a specific region and time period', 'C. A forecast of upper winds and temperatures', 'D. A pilot report summary for a region'], correct: 1, explanation: 'The GAF provides a graphical representation of forecast weather for low-level flights. It shows cloud layers, visibility, significant weather, icing, and turbulence in defined areas. A common weak area in CMET.', reference: 'CASA CMET Syllabus / BOM GAF Guide' },
    { question: 'What weather phenomenon is associated with a backing wind in the Southern Hemisphere?', options: ['A. Backing wind indicates deteriorating weather — associated with approaching low pressure or warm front', 'B. Backing wind always indicates improving conditions', 'C. Backing wind in Australia means the wind is turning clockwise', 'D. Backing winds occur only above the tropopause'], correct: 0, explanation: 'In the Southern Hemisphere, a backing wind (turning anticlockwise) indicates deteriorating weather, typically associated with an approaching low or warm front. A veering wind (turning clockwise) generally indicates improving conditions.', reference: 'CASA CMET Syllabus / Meteorology Study Guide' },
  ],
  'Navigation': [
    { question: 'An aircraft departs at 0830 UTC tracking 270 degrees M at a groundspeed of 120 kt. The destination is 240 nm away. What is the ETA?', options: ['A. 1030 UTC', 'B. 1050 UTC', 'C. 1110 UTC', 'D. 1130 UTC'], correct: 0, explanation: 'Time = Distance / Groundspeed = 240 / 120 = 2.0 hours. ETA = 0830 + 0200 = 1030 UTC.', reference: 'CASA CNAV Syllabus / Navigation Study Guide' },
    { question: 'Using the 1-in-60 rule: An aircraft has flown 90 nm and is 6 nm to the right of track. What heading change is required to parallel the planned track?', options: ['A. 2 degrees left', 'B. 4 degrees left', 'C. 6 degrees left', 'D. 8 degrees left'], correct: 1, explanation: 'Track error = (6/90) x 60 = 4 degrees. To parallel track (not regain), apply 4 degrees correction toward track — turn 4 degrees LEFT.', reference: 'CASA CNAV Syllabus / Navigation Study Guide' },
    { question: 'What is the difference between track and heading in navigation?', options: ['A. Track and heading are the same', 'B. Track is the actual path over the ground; heading is the direction the aircraft nose points — they differ due to wind', 'C. Track is magnetic; heading is true', 'D. Track is the filed route; heading is the actual direction flown'], correct: 1, explanation: 'Track is the actual path of the aircraft over the ground. Heading is the direction the aircraft nose points. They differ because wind causes drift — the aircraft must head into the wind to maintain the desired track.', reference: 'CASA CNAV Syllabus / Navigation Study Guide' },
    { question: 'What is LSALT and what clearance does it provide?', options: ['A. Altitude providing 500 ft clearance within 5 nm of track', 'B. Lowest safe altitude providing 1000 ft terrain clearance within 5 nm of track (10 nm in mountainous areas)', 'C. Minimum altitude for IFR flight', 'D. Altitude at which radar coverage is guaranteed'], correct: 1, explanation: 'LSALT provides a minimum of 1000 ft terrain and obstacle clearance within 5 nm either side of track. Pilots calculate it from topographic charts or use published LSALT grids in the AIP.', reference: 'CASA CNAV Syllabus / AIP ENR 1.1' },
    { question: 'What is the required rate of climb to maintain a 5% gradient at a groundspeed of 120 kt?', options: ['A. 600 ft/min', 'B. 800 ft/min', 'C. 1000 ft/min', 'D. 1200 ft/min'], correct: 2, explanation: 'ROC (ft/min) = GS (kt) x gradient (%) / 0.6 = 120 x 5 / 0.6 = 1000 ft/min. A common weak area in CNAV.', reference: 'CASA CNAV Syllabus / Navigation Study Guide' },
    { question: 'On a WAC at 1:1000000 scale, a pilot measures 8 cm between two points. What is the ground distance in nm?', options: ['A. 43 nm', 'B. 53 nm', 'C. 80 nm', 'D. 48 nm'], correct: 0, explanation: '1:1000000 — 1 cm = 10 km. 8 cm = 80 km. Converting: 80 / 1.852 = 43.2 nm ≈ 43 nm.', reference: 'CASA CNAV Syllabus / Chart Reading' },
    { question: 'What information does a VOR radial provide?', options: ['A. Distance from the station only', 'B. A magnetic bearing FROM the station — two radials from different VORs provide a position fix', 'C. Bearing TO the station from the aircraft', 'D. VOR only works combined with DME'], correct: 1, explanation: 'A VOR radial is a magnetic bearing FROM the station (QDR). If you are on the 090 radial, you are due east of the station. Two VOR radials from different stations provide a position fix.', reference: 'CASA CNAV Syllabus / Radio Navigation Study Guide' },
    { question: 'What is the difference between variation and deviation in compass navigation?', options: ['A. Variation is local to individual aircraft; deviation is the same everywhere', 'B. Variation is the angular difference between true and magnetic north; deviation is the error caused by the aircraft own magnetic fields', 'C. They are the same thing', 'D. Deviation converts true to magnetic; variation converts magnetic to compass'], correct: 1, explanation: 'Variation is the angle between true and magnetic north — it varies geographically. Deviation is the compass error caused by the aircraft own electrical systems, recorded on the compass deviation card.', reference: 'CASA CNAV Syllabus / Navigation Study Guide' },
    { question: 'An aircraft is at the halfway point of a 180 nm flight and is 9 nm left of track. What total heading change is required to track directly to destination?', options: ['A. 6 degrees right', 'B. 12 degrees right', 'C. 9 degrees right', 'D. 18 degrees right'], correct: 3, explanation: 'Halfway = 90 nm flown. Track error = (9/90) x 60 = 6 degrees. Remaining distance = 90 nm. Closing angle = (9/90) x 60 = 6 degrees. Total correction = track error + closing angle = 6 + 6 = 12 degrees... wait — at halfway, closing angle equals track error. Total = 6 + 6 = 12 degrees RIGHT. Answer B.', reference: 'CASA CNAV Syllabus / 1-in-60 Rule' },
    { question: 'What is the purpose of the ERSA and what information does it contain?', options: ['A. Weather forecasts for en-route flight', 'B. Detailed aerodrome information including facilities, frequencies, operating hours, fuel availability, and procedures for all Australian aerodromes', 'C. Only IFR approach procedures', 'D. A substitute for aeronautical charts'], correct: 1, explanation: 'The ERSA contains detailed aerodrome information including CTAF/tower frequencies, runways, lighting, fuel types and hours, customs, facilities, circuit direction, and local procedures.', reference: 'CASA CNAV Syllabus / ERSA Introduction' },
  ],
  'Operations, Performance and Planning': [
    { question: 'An aircraft burns 42 L/hr at cruise. A VFR day flight under Part 91 requires 2 hours 15 minutes. What is the minimum fuel required to depart legally?', options: ['A. 94.5 litres', 'B. 126 litres', 'C. 78 litres', 'D. 110 litres'], correct: 1, explanation: 'Trip fuel = 42 x 2.25 = 94.5 L. Reserve (45 min) = 42 x 0.75 = 31.5 L. Total = 94.5 + 31.5 = 126 L.', reference: 'CASR Part 91 MOS Chapter 19 / CAO 20.9' },
    { question: 'What is the definition of Zero Fuel Weight and Maximum Zero Fuel Weight?', options: ['A. ZFW is the aircraft weight with minimum fuel; MZFW is the maximum empty weight', 'B. ZFW is total weight minus usable fuel; MZFW is the maximum weight the structure can sustain without wing fuel providing bending relief', 'C. ZFW equals basic empty weight plus payload; MZFW is set by performance', 'D. ZFW and MZFW are the same thing'], correct: 1, explanation: 'ZFW is total weight excluding usable fuel. MZFW is the maximum certificated weight without usable fuel — set by structural limits at the wing root. Exceeding MZFW can cause structural damage even if MTOW is not exceeded.', reference: 'CASA CFPA Syllabus / Mass and Balance Study Guide' },
    { question: 'An aircraft has BEW 780 kg, MTOW 1300 kg, fuel 144 kg, pilot 80 kg. What is the maximum passenger and baggage weight?', options: ['A. 376 kg', 'B. 296 kg', 'C. 440 kg', 'D. 520 kg'], correct: 1, explanation: 'Maximum payload = MTOW - BEW - Fuel - Pilot = 1300 - 780 - 144 - 80 = 296 kg.', reference: 'CASA CFPA Syllabus / Mass and Balance Study Guide' },
    { question: 'What factors increase takeoff distance required beyond the POH standard distance?', options: ['A. Headwind, upslope, low density altitude, dry runway', 'B. Tailwind, upslope, high density altitude, grass runway, high gross weight', 'C. High gross weight and flap extension only', 'D. TODR is fixed regardless of conditions'], correct: 1, explanation: 'TODR increases with: tailwind, upslope, high density altitude (high, hot, humid), grass/contaminated runway, and high gross weight. All factors from the performance graph must be applied.', reference: 'CASA CFPA Syllabus / RPL PPL CPL Workbook' },
    { question: 'What is ramp weight and how does it differ from takeoff weight?', options: ['A. They are identical', 'B. Ramp weight is total weight at engine start including taxi fuel; takeoff weight is ramp weight minus fuel burned during taxi', 'C. Ramp weight includes the weight of the ramp crew', 'D. Ramp weight is the weight after landing'], correct: 1, explanation: 'Ramp weight includes all fuel at engine start. Takeoff weight is ramp weight minus taxi fuel. MTOW applies at brake release, not at engine start.', reference: 'CASA CFPA Syllabus / Mass and Balance Study Guide' },
    { question: 'What is the effect of a headwind on takeoff distance required?', options: ['A. A headwind increases TODR', 'B. A headwind decreases TODR — a headwind of 10% of liftoff speed reduces TODR by approximately 19%', 'C. Wind has no effect on TODR', 'D. A headwind increases TODR by the wind speed percentage'], correct: 1, explanation: 'A headwind decreases TODR because the aircraft already has airspeed before it starts rolling. As a rule, 10% of liftoff speed in headwind reduces TODR by approximately 19%.', reference: 'CASA CFPA Syllabus / Performance Study Guide' },
    { question: 'What is the purpose of MAC (Mean Aerodynamic Chord) in mass and balance?', options: ['A. MAC is used to calculate wing area', 'B. MAC is a reference chord length used to express CG position as a percentage', 'C. MAC is the maximum allowed chord length', 'D. MAC is used only in jet transport aircraft'], correct: 1, explanation: 'MAC is used to express CG position as a percentage. A CG of 25% MAC means the CG is 25% of the MAC length from the leading edge. This provides a consistent reference regardless of aircraft size.', reference: 'CASA CFPA Syllabus / Mass and Balance Study Guide' },
    { question: 'Under Part 91 MOS Chapter 19, what is the fuel reserve for a piston VFR day flight?', options: ['A. 30 minutes at cruise power', 'B. 45 minutes at cruise power', 'C. 1 hour at cruise power', 'D. 10% of trip fuel'], correct: 1, explanation: 'Under CASR Part 91 MOS Chapter 19 Table 19.02, piston aeroplanes under 5700 kg on VFR day flights must carry trip fuel plus 45 minutes reserve at cruise power.', reference: 'CASR Part 91 MOS Chapter 19 Table 19.02' },
    { question: 'What is Va and why does it decrease as aircraft weight decreases?', options: ['A. Va increases as weight decreases', 'B. Va decreases as weight decreases because lighter aircraft stall at lower speeds — the aircraft stalls before reaching the structural limit load factor at a lower speed', 'C. Va remains constant regardless of weight', 'D. Va only changes with altitude'], correct: 1, explanation: 'Va is the speed below which full control deflection will stall the aircraft before exceeding the structural limit load factor. Since stall speed decreases with weight, Va also decreases with weight.', reference: 'CASA CFPA Syllabus / Aircraft Flight Manual' },
    { question: 'What are the consequences of operating outside the aft CG limit?', options: ['A. Reduced elevator effectiveness and higher stall speed only', 'B. Reduced or negative longitudinal stability — the aircraft may pitch up uncontrollably and enter an irrecoverable stall', 'C. CG limits only affect passenger comfort', 'D. Aft CG only affects fuel consumption'], correct: 1, explanation: 'Operating aft of the CG limit is potentially fatal. Reduced stability means the aircraft may pitch up uncontrollably. Forward CG reduces elevator effectiveness; aft CG removes stability entirely.', reference: 'CASA CFPA Syllabus / Mass and Balance Study Guide' },
  ],
  'Flight Rules & Air Law': [
    { question: 'What are the VFR visibility and cloud clearance requirements in Class G airspace at and below 3000 ft AMSL by day?', options: ['A. 5 km visibility, 1000 ft above, 1000 ft below, 1 nm horizontally', 'B. 1500 m flight visibility, clear of cloud', 'C. 5000 m visibility, 500 ft below, 1000 ft above, 600 m horizontally', 'D. 8 km visibility, CAVOK only'], correct: 1, explanation: 'In Class G airspace at or below 3000 ft AMSL or 1000 ft AGL, the minimum VFR requirements by day are 1500 m flight visibility and clear of cloud.', reference: 'CASR Part 91 MOS / AIP ENR 1.2' },
    { question: 'The CLWA exam requires an 80% pass mark. What is the pass mark for most other CPL exams?', options: ['A. 75%', 'B. 70%', 'C. 65%', 'D. 80% for all exams'], correct: 1, explanation: 'Most CPL exams (CHUF, CNAV, CMET, CADA, CFPA, CSYA) require 70% to pass. CLWA (Air Law) requires 80% — reflecting the critical nature of regulatory knowledge.', reference: 'CASA CLWA Syllabus / CASR' },
    { question: 'When two aircraft are converging at approximately the same altitude, which aircraft gives way?', options: ['A. The slower aircraft gives way to the faster', 'B. The aircraft with the other on its LEFT gives way — the aircraft on the right has right of way', 'C. The higher aircraft gives way to the lower', 'D. IFR aircraft give way to VFR traffic'], correct: 1, explanation: 'Under CASR Part 91 rules of the air: when two aircraft are converging, the aircraft that has the other on its LEFT must give way. The aircraft on the RIGHT has right of way.', reference: 'CASR Part 91.080 / AIP ENR 1.1' },
    { question: 'What are the VFR cloud clearance requirements above 3000 ft AMSL in Class G airspace?', options: ['A. 1500 m visibility, clear of cloud', 'B. 5 km visibility, 1000 ft above, 1000 ft below, 1 nm horizontally from cloud', 'C. 8 km visibility, CAVOK', 'D. 3 km visibility, 500 ft vertically, 600 m horizontally'], correct: 1, explanation: 'Above 3000 ft AMSL (or 1000 ft AGL) in Class G airspace: 5 km visibility, 1000 ft above, 1000 ft below, 1 nm horizontally from cloud. More stringent than the low-level minima.', reference: 'CASR Part 91 MOS / AIP ENR 1.2' },
    { question: 'What are the requirements for operating in a Mandatory Broadcast Zone (MBZ)?', options: ['A. No radio required', 'B. Pilots must make position reports on the published MBZ frequency at specified reporting points', 'C. ATC clearance is required before entering', 'D. MBZs only apply to IFR aircraft'], correct: 1, explanation: 'An MBZ requires broadcasts on the published frequency at specific points. There is no ATC — pilots self-coordinate by broadcasting their intentions and position.', reference: 'AIP ENR 1.1 / CASR Part 91' },
    { question: 'What pilot maintenance tasks are permitted under CASR Part 43 Schedule 8?', options: ['A. Pilots cannot perform any maintenance', 'B. Pilots may perform certain simple tasks listed in Schedule 8 — including replacing consumables and minor adjustments specified in the maintenance manual', 'C. Pilots may perform any maintenance with a CPL', 'D. Pilots may maintain only if supervised by a LAME'], correct: 1, explanation: 'CASR Part 43 Schedule 8 lists specific maintenance tasks that a licensed pilot may perform — such as replacing light globes, cleaning, and checking fluids. A common weak area in CLWA.', reference: 'CASR Part 43 Schedule 8' },
    { question: 'What right of way rules apply between different categories of aircraft?', options: ['A. Faster aircraft always have right of way', 'B. Less maneuverable aircraft have right of way — order is: balloons, gliders, airships, aircraft towing loads, powered aircraft', 'C. Larger aircraft always have right of way', 'D. IFR aircraft always have right of way over VFR'], correct: 1, explanation: 'Right of way goes to less maneuverable aircraft: balloons first, then gliders, airships, aircraft towing slung loads, then powered aircraft. Aircraft in distress have right of way over all.', reference: 'CASR Part 91 / AIP ENR 1.1' },
    { question: 'To act as pilot in command under CASR Part 61, what are the key requirements?', options: ['A. Hold any grade of pilot licence and a current medical', 'B. Hold appropriate pilot licence for the aircraft category, hold a current medical of the required class, and comply with recency requirements', 'C. Hold a CPL for all aircraft operations', 'D. Licence requirements only apply to commercial operations'], correct: 1, explanation: 'To act as PIC: hold the appropriate licence for the category/class, hold a current medical certificate, and meet recency requirements (typically 3 takeoffs and landings in preceding 90 days for day VFR).', reference: 'CASR Part 61 / CASA CLWA Syllabus' },
    { question: 'What is the definition of a controlled aerodrome and what communication requirements apply?', options: ['A. Any aerodrome with a sealed runway', 'B. An aerodrome with an operating control tower — two-way radio must be established before taxiing, and ATC clearances must be obtained before all movements', 'C. Any aerodrome listed in ERSA', 'D. An aerodrome inside Class C airspace only'], correct: 1, explanation: 'A controlled aerodrome has an operating ATC tower. Requirements: establish two-way radio before moving, obtain taxi/takeoff/landing clearances, follow all ATC instructions, and read back clearances as required.', reference: 'CASR Part 91 / AIP ENR 1.1' },
    { question: 'What is a SARTIME and when is it required?', options: ['A. Mandatory for all VFR flights', 'B. A time lodged with NAIPS or a responsible person — if the aircraft has not arrived or reported by this time, SAR action is initiated', 'C. Only required for IFR flights', 'D. Only required for flights over water'], correct: 1, explanation: 'A SARTIME (SAR action time) is lodged with NAIPS or a responsible person. If the aircraft has not reported by the SARTIME, SAR action begins. Mandatory for many operations including remote area and overwater flights.', reference: 'CASR Part 91 / AIP ENR 1.10' },
  ],
  'Aircraft General Knowledge': [
    { question: 'What does a HIGH positive ammeter reading immediately after engine start indicate?', options: ['A. Battery fully charged', 'B. Normal — the alternator is recharging the battery depleted during start', 'C. Electrical fault', 'D. Overvoltage condition'], correct: 1, explanation: 'Immediately after engine start, a high positive ammeter is NORMAL — the alternator is recharging the battery. Once recharged, the reading reduces. A ZERO reading indicates the alternator is not charging — an abnormal indication. A common weak area in CSYA.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What is the correct indication when carburettor heat is applied and ice IS present?', options: ['A. Immediate RPM increase', 'B. Initial RPM drop followed by a RPM rise as ice melts', 'C. No change in RPM', 'D. Immediate engine roughness then shutdown'], correct: 1, explanation: 'When carb heat is applied and ice IS present: RPM initially drops further (hot air is less dense) then RISES as ice melts. If no ice, RPM drops and stays down. A common weak area in CSYA.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What are the identifying colours for AVGAS 100LL and AVGAS 100?', options: ['A. AVGAS 100LL is red; AVGAS 100 is blue', 'B. AVGAS 100LL is blue; AVGAS 100 is green', 'C. Both are colourless', 'D. AVGAS 100LL is green; AVGAS 100 is red'], correct: 1, explanation: 'AVGAS 100LL is dyed BLUE. AVGAS 100 is dyed GREEN. Jet A-1 is colourless/straw. Using Jet A-1 in a piston engine will cause engine failure. Fuel identification is a common weak area in CSYA.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'Why do aircraft piston engines have two magnetos?', options: ['A. Magnetos provide electrical power to avionics — two are for redundancy', 'B. Magnetos are self-contained engine-driven ignition devices — two provide redundancy so the engine continues if one fails', 'C. One magneto is for starting, the other for normal operation', 'D. Magnetos control fuel mixture'], correct: 1, explanation: 'Magnetos are self-powered ignition generators that do not require the aircraft electrical system. Each fires one set of spark plugs per cylinder. If one magneto fails, the engine continues on the other. A common weak area in CSYA.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What is a turbocharger and how does it differ from a supercharger?', options: ['A. Both are identical devices', 'B. A turbocharger uses exhaust gas to drive a compressor maintaining manifold pressure at altitude; a supercharger is driven by the engine crankshaft — turbocharger uses waste energy', 'C. A turbocharger increases RPM; a supercharger increases manifold pressure', 'D. Superchargers are for low altitude; turbochargers for above 10000 ft'], correct: 1, explanation: 'A turbocharger uses exhaust gas energy to spin a turbine driving a compressor. A supercharger is mechanically driven by the engine. Turbochargers are more efficient as they use waste exhaust energy. A common weak area in CSYA.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What is the purpose of the mixture control at altitude?', options: ['A. Mixture control adjusts fuel pressure', 'B. At altitude, air is less dense so the engine runs too rich — leaning restores the correct fuel-air ratio, reducing roughness and improving fuel consumption', 'C. The mixture control is only used during engine start', 'D. Too rich mixture increases engine temperature'], correct: 1, explanation: 'As altitude increases, air density decreases causing over-rich mixture. Symptoms: rough running, high fuel consumption, black smoke, power loss. Leaning restores the correct ratio.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What instruments are powered by the aircraft vacuum system?', options: ['A. The vacuum system powers the fuel pump', 'B. The vacuum system powers the attitude indicator and directional indicator — failure causes these instruments to slowly become unreliable', 'C. The vacuum system powers the pitot-static instruments', 'D. The vacuum system only powers the autopilot'], correct: 1, explanation: 'The vacuum system powers the gyroscopic instruments: attitude indicator (AI) and directional indicator (DI). Vacuum failure causes these to slowly precess and become unreliable within 10-15 minutes. The turn coordinator is electrically powered.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What preflight fuel check should be performed and what are you looking for?', options: ['A. Only check fuel quantity', 'B. Drain and visually inspect fuel samples from all sumps — check for water (globules or separate lower layer), sediment, and correct fuel colour', 'C. Fuel checks only required after refuelling', 'D. Smell the fuel only'], correct: 1, explanation: 'Fuel sump checks are critical. Water contamination appears as clear globules or a separate lower layer. Water does not burn and can cause engine failure. Sump drains should be checked from all low points until consistently clean fuel is obtained.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What is the function of a constant-speed propeller governor?', options: ['A. It prevents the propeller exceeding maximum RPM', 'B. The governor automatically adjusts blade pitch to maintain the RPM set by the pilot — increases pitch when RPM rises, decreases pitch when RPM falls', 'C. It synchronises RPM between engines', 'D. It controls propeller feathering during engine failure'], correct: 1, explanation: 'The propeller governor senses actual RPM and adjusts blade pitch to maintain the selected RPM. If RPM rises, pitch increases (more load). If RPM falls, pitch decreases (less load).', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
    { question: 'What is the purpose of a magneto ground check and what is an acceptable RPM drop?', options: ['A. The mag check verifies the aircraft electrical system', 'B. The mag check verifies both magnetos are firing correctly — a drop of up to 125 RPM on each mag with no more than 50 RPM difference between the two is typically acceptable', 'C. Any RPM drop indicates a fault', 'D. The mag check only applies to twin-engine aircraft'], correct: 1, explanation: 'The magneto check verifies each magneto is firing correctly. Typical limits: maximum 125 RPM drop on either mag, maximum 50 RPM difference between mags. An excessive drop or large difference indicates a fault — commonly a fouled spark plug.', reference: 'CASA CSYA Syllabus / Aircraft General Knowledge Study Guide' },
  ],
  'PPL Theory': [
    { question: 'What is the minimum weather for VFR flight by day outside controlled airspace below 3000 ft AMSL?', options: ['A. 1500 m visibility and clear of cloud', 'B. 5000 m visibility and 1000 ft ceiling', 'C. 3000 m visibility and 500 ft ceiling', 'D. 8 km visibility'], correct: 0, explanation: 'For VFR flight outside controlled airspace below 3000 ft AMSL or 1000 ft AGL, the minimum is 1500 m flight visibility and clear of cloud.', reference: 'AIP ENR 1.2 / CASR Part 91' },
    { question: 'What does QNH mean and when is it used?', options: ['A. Height above the aerodrome reference point', 'B. Altimeter setting that causes the altimeter to read altitude above mean sea level at the aerodrome', 'C. Standard pressure setting of 1013.25 hPa', 'D. Height above the highest terrain within 5 nm'], correct: 1, explanation: 'QNH is set so that the altimeter reads altitude above mean sea level at the aerodrome level. It is used for all flights below the transition altitude.', reference: 'AIP GEN 2.2 / AIP ENR 1.7' },
    { question: 'What is the standard traffic circuit direction at a non-controlled aerodrome?', options: ['A. Right hand', 'B. Left hand unless otherwise published in ERSA or by NOTAM', 'C. Pilot discretion based on wind', 'D. Depends on runway orientation'], correct: 1, explanation: 'The standard circuit direction at a non-controlled aerodrome is LEFT HAND unless a right-hand circuit is published in ERSA or by NOTAM.', reference: 'AIP ENR 1.1 / ERSA' },
    { question: 'What is a METAR and how often is it issued at major Australian aerodromes?', options: ['A. A forecast issued every 6 hours', 'B. A routine aviation weather observation issued every 30 minutes at major aerodromes', 'C. A special observation issued only when weather changes', 'D. A pilot weather report'], correct: 1, explanation: 'A METAR is a routine aviation weather observation issued at regular intervals — typically every 30 minutes at major Australian aerodromes.', reference: 'AIP GEN 3.5 / BOM METAR Guide' },
    { question: 'What does VFR stand for and what are the fundamental principles?', options: ['A. Very Fast Route', 'B. Visual Flight Rules — the pilot navigates by visual reference to the ground and maintains VMC', 'C. Verified Flight Requirements', 'D. Vertical Flight Regulations'], correct: 1, explanation: 'VFR (Visual Flight Rules) means the pilot navigates primarily by visual reference to the ground, maintains VMC, and is responsible for see-and-avoid collision avoidance.', reference: 'CASR Part 91 / AIP ENR 1.2' },
    { question: 'What are the coloured arcs on the Airspeed Indicator and what do they mean?', options: ['A. The colours are decorative', 'B. White arc = flap operating range (Vs0 to Vfe); Green arc = normal operating range (Vs1 to Vno); Yellow arc = caution range; Red line = Vne', 'C. Green means safe, red means dangerous — no specific speeds', 'D. The arcs only apply to instrument-rated pilots'], correct: 1, explanation: 'ASI coloured arcs: White (Vs0 to Vfe) = flap range; Green (Vs1 to Vno) = normal range; Yellow (Vno to Vne) = caution, smooth air only; Red line = Vne (never exceed).', reference: 'CASA PPL Study Guide / Aircraft Flight Manual' },
    { question: 'What action should a VFR pilot take if they inadvertently enter IMC?', options: ['A. Continue and hope it clears', 'B. Immediately execute a 180-degree turn to exit IMC, maintain control by reference to instruments, declare MAYDAY, and request ATC assistance', 'C. Climb above the cloud', 'D. Descend below cloud base and continue at low level'], correct: 1, explanation: 'VFR into IMC is one of the most dangerous scenarios for non-instrument-rated pilots. The immediate action is a 180-degree turn to exit. Declare MAYDAY and request ATC assistance. Continuing into IMC causes spatial disorientation and loss of control.', reference: 'CASA PPL Study Guide / Human Factors' },
    { question: 'What is a NOTAM and where can pilots find them?', options: ['A. A weather forecast found in BOM publications', 'B. A Notice to Air Missions — found in NAIPS (National Aeronautical Information Processing System)', 'C. A mandatory CASA safety directive found only at airports', 'D. A navigation chart update published monthly'], correct: 1, explanation: 'A NOTAM contains information essential to flight operations including airspace restrictions and unserviceable facilities. Pilots check NOTAMs via NAIPS (naips.airservicesaustralia.com) before every flight.', reference: 'AIP GEN 3.1 / NAIPS' },
    { question: 'What is the purpose of draining fuel sumps before flight?', options: ['A. To check fuel quantity only', 'B. To check for water contamination (appears as clear globules or a separate lower layer) and correct fuel type', 'C. Only required after refuelling', 'D. To reduce fuel weight before takeoff'], correct: 1, explanation: 'Fuel sump drains check for water (clear globules or separate layer at bottom) and verify correct fuel type and colour. Water does not burn and can cause engine failure. All sump drains must be checked until clean fuel is obtained.', reference: 'CASA PPL Study Guide / Aircraft Flight Manual' },
    { question: 'What is the CTAF frequency and what mandatory calls are required at a non-towered aerodrome?', options: ['A. 121.5 MHz — emergency calls only', 'B. The published CTAF frequency (often 126.7 MHz) — mandatory calls at: taxiing, joining, final, taking the runway, airborne, and clear of the landing area', 'C. 118.1 MHz — no mandatory calls', 'D. Any available frequency — calls are optional'], correct: 1, explanation: 'CTAF (Common Traffic Advisory Frequency) requires mandatory broadcasts at specified points: before taxiing, joining the circuit, on final, taking the runway, airborne, and when clear of the landing area.', reference: 'AIP ENR 1.1 / CASR Part 91' },
  ],
  'Flight Planning': [
    { question: 'An aircraft burns 38 L/hr at cruise. A VFR day flight under Part 91 takes 1 hour 45 minutes. What is the minimum fuel required?', options: ['A. 66.5 litres', 'B. 95 litres', 'C. 57 litres', 'D. 85 litres'], correct: 0, explanation: 'Trip fuel = 38 x 1.75 = 66.5 L. Reserve (45 min) = 38 x 0.75 = 28.5 L. Total = 66.5 + 28.5 = 95 L. Answer is B — 95 litres.', reference: 'CASR Part 91 MOS Chapter 19 / CAO 20.9' },
    { question: 'What is MTOW and what legal obligation does it impose?', options: ['A. A manufacturer recommendation only', 'B. Maximum Takeoff Weight — the maximum certificated weight at which the aircraft may commence the takeoff roll. Exceeding MTOW makes the flight illegal and the aircraft unairworthy', 'C. Minimum Takeoff Weight', 'D. Only relevant for commercial operations'], correct: 1, explanation: 'MTOW is a structural and performance limit set in the AFM. Exceeding MTOW is illegal under CASR, voids the certificate of airworthiness, and may invalidate insurance. The pilot in command is responsible.', reference: 'CASR Part 21 / CASR Part 91 / Aircraft Flight Manual' },
    { question: 'What is pressure altitude and how is it calculated?', options: ['A. The height shown on the altimeter set to local QNH', 'B. The altitude indicated when the altimeter is set to 1013.25 hPa — approximately: PA = Field Elevation + (1013 - QNH) x 27 ft per hPa', 'C. Pressure altitude equals true altitude', 'D. Only relevant above 10000 ft'], correct: 1, explanation: 'Pressure altitude is used in performance graph calculations. If QNH = 998 and field elevation = 500 ft: PA = 500 + (1013-998) x 27 = 905 ft. Performance graphs require pressure altitude, not field elevation.', reference: 'CASA CFPA Syllabus / Performance Study Guide' },
    { question: 'What factors must be considered when calculating TODR from a performance graph?', options: ['A. Only aircraft weight and wind', 'B. Pressure altitude, OAT, aircraft weight, wind component, runway surface, and runway slope', 'C. Only density altitude and wind', 'D. Performance graphs not required under 5700 kg'], correct: 1, explanation: 'TODR calculation requires: pressure altitude, OAT, gross weight, headwind/tailwind component, runway surface (grass adds 15-20%), and runway slope. All factors must be applied correctly.', reference: 'CASA CFPA Syllabus / RPL PPL CPL Workbook' },
    { question: 'What is the standard fuel reserve for a Part 91 VFR night flight for a piston aircraft under 5700 kg?', options: ['A. 1 hour reserve', 'B. 45 minutes reserve at cruise power — same as VFR day under Part 91', 'C. 30 minutes reserve', 'D. Alternate fuel plus 45 minutes'], correct: 1, explanation: 'Under CASR Part 91 MOS Chapter 19, VFR night for piston aircraft under 5700 kg requires trip fuel plus 45 minutes reserve — the same as VFR day.', reference: 'CASR Part 91 MOS Chapter 19 Table 19.02' },
    { question: 'An aircraft has BEW 850 kg, MTOW 1400 kg, fuel 150 kg. What is the maximum payload?', options: ['A. 400 kg', 'B. 550 kg', 'C. 300 kg', 'D. 450 kg'], correct: 0, explanation: 'Maximum payload = MTOW - BEW - Fuel = 1400 - 850 - 150 = 400 kg.', reference: 'CASA CFPA Syllabus / Mass and Balance Study Guide' },
    { question: 'What is the consequence of operating forward of the CG limit?', options: ['A. Reduced longitudinal stability and possible pitch-up', 'B. Insufficient elevator authority to rotate or flare, higher stall speed, increased trim drag', 'C. No effect on handling', 'D. Increased fuel consumption only'], correct: 1, explanation: 'Forward CG: insufficient elevator to rotate for takeoff or flare for landing, higher stall speed (more trim required), and increased trim drag reducing performance. Both forward and aft limits must be respected.', reference: 'CASA CFPA Syllabus / Mass and Balance Study Guide' },
    { question: 'What is V2 and why is it significant for multi-engine aircraft?', options: ['A. V2 is the same as Vr (rotation speed)', 'B. V2 is the takeoff safety speed — minimum speed at screen height (35 ft) guaranteeing required climb gradient with one engine inoperative', 'C. V2 is the speed for flap retraction', 'D. V2 is the maximum speed for gear retraction'], correct: 1, explanation: 'V2 is the minimum airspeed at screen height (35 ft) that guarantees the required obstacle clearance climb gradient with one engine inoperative. Crews must maintain at least V2 during the initial climb.', reference: 'CASA CFPA Syllabus / Performance Study Guide' },
    { question: 'Under Part 135 MOS, how do fuel requirements differ from Part 91 for charter operations?', options: ['A. Same as Part 91', 'B. Part 135 has more stringent requirements potentially including alternate fuel, holding fuel, and contingency fuel in addition to trip fuel', 'C. Part 135 requires less fuel for short flights', 'D. Part 135 fuel requirements are less strict'], correct: 1, explanation: 'Part 135 (charter/air transport) has more stringent fuel requirements. Requirements vary by operation type and may include: trip fuel, contingency fuel, alternate fuel, holding fuel, and final reserve. CFPA questions specify Part 91 or Part 135.', reference: 'CASR Part 135 MOS Chapter 7 / CASA CFPA Syllabus' },
    { question: 'What is the effect of high density altitude on takeoff distance required?', options: ['A. High density altitude reduces TODR', 'B. High density altitude significantly increases TODR — less dense air reduces engine power and propeller efficiency, requiring higher TAS to achieve flying speed', 'C. Density altitude has no effect on TODR', 'D. High density altitude only affects climb performance'], correct: 1, explanation: 'High density altitude (high, hot, humid) means less dense air — reduced engine power, reduced propeller thrust. The aircraft must achieve a higher TAS to reach flying speed, significantly increasing TODR. Critical for hot day operations at elevated aerodromes.', reference: 'CASA CFPA Syllabus / Performance Study Guide' },
  ],
  'Instrument Rating': [
    { question: 'What is Decision Altitude (DA) and what action is required when reaching it?', options: ['A. DA is reached and the pilot must land regardless of visibility', 'B. At DA the pilot must have required visual reference to continue — if not visible, an immediate missed approach must be executed', 'C. DA is the altitude at which autopilot disconnects', 'D. DA is only applicable in IMC'], correct: 1, explanation: 'DA is the altitude at which the pilot must decide to land or go around. If the required visual reference is not clearly visible, an immediate missed approach must be initiated. Descending below DA without visual reference is prohibited.', reference: 'ICAO Doc 8168 / AIP ENR 1.5 / CASR Part 91' },
    { question: 'What is the difference between a precision and non-precision approach?', options: ['A. Precision approaches use GPS; non-precision use ground-based navaids', 'B. Precision approaches provide lateral AND vertical electronic guidance with a Decision Altitude; non-precision provide lateral guidance only with a Minimum Descent Altitude', 'C. Precision approaches are only at major aerodromes', 'D. Non-precision approaches have lower minima'], correct: 1, explanation: 'Precision (ILS, GLS, PAR): lateral and vertical electronic guidance, Decision Altitude. Non-precision (VOR, NDB, RNAV): lateral guidance only, Minimum Descent Altitude. The crew manages descent themselves on non-precision.', reference: 'ICAO Doc 8168 / AIP ENR 1.5' },
    { question: 'What is an NDB and how does the ADF work?', options: ['A. An NDB transmits a directional signal toward the runway', 'B. An NDB transmits an omnidirectional signal — the ADF needle points toward the NDB, allowing the pilot to track to or from the beacon', 'C. An NDB provides both distance and bearing', 'D. NDBs are only used for en-route navigation'], correct: 1, explanation: 'An NDB transmits an omnidirectional carrier wave. The ADF needle points TO the NDB. NDBs are susceptible to interference from thunderstorms, coastal refraction, and night effect.', reference: 'AIP ENR 4.1 / CASA IREX Syllabus' },
    { question: 'What is the purpose of the localiser on an ILS system?', options: ['A. The localiser provides vertical guidance', 'B. The localiser provides lateral (left/right) guidance to the runway centreline — full-scale deflection is typically 2.5 degrees either side of centreline', 'C. The localiser only provides guidance within 5 nm', 'D. The localiser provides both lateral and vertical guidance'], correct: 1, explanation: 'The localiser is the lateral (azimuth) guidance component of the ILS. It provides precision lateral guidance to the runway centreline. The glideslope provides vertical guidance.', reference: 'ICAO Doc 8168 / AIP ENR 1.5' },
    { question: 'When is an IFR alternate aerodrome required?', options: ['A. Always required for IFR flights', 'B. When the forecast weather at the destination is below the applicable approach minima during the planned arrival period', 'C. Only for night IFR flights', 'D. Only for flights over 1 hour'], correct: 1, explanation: 'An IFR alternate is required when the destination weather is forecast to be below the applicable minima during the planned arrival window. The alternate must also meet its own forecast weather requirements.', reference: 'CASR Part 91 / CAO 20.9' },
    { question: 'What are the three standard holding pattern entries?', options: ['A. There is only one entry method', 'B. Direct entry, Parallel entry, and Teardrop/Offset entry — determined by the aircraft heading relative to the holding pattern outbound course', 'C. Holding entries are at pilot discretion', 'D. There are five types based on speed'], correct: 1, explanation: 'Three holding entries: Direct (turn immediately onto outbound), Parallel (fly parallel to outbound, turn to re-intercept), Teardrop (fly at 30 degrees offset for 1 minute then turn to intercept inbound). Entry depends on sector of arrival.', reference: 'ICAO Doc 8168 / AIP ENR 1.5' },
    { question: 'What is Minimum Safe Altitude (MSA) on an approach chart?', options: ['A. The altitude to fly during the approach', 'B. Minimum altitude providing 300 m obstacle clearance within 25 nm of the navaid — for EMERGENCY USE ONLY, provides no navigation guidance', 'C. The decision altitude for the approach', 'D. The minimum altitude for radar vectoring'], correct: 1, explanation: 'MSA provides 300 m obstacle clearance within 25 nm of the airport/navaid. It is for EMERGENCY USE ONLY — not for normal operations. It provides no navigation guidance, only obstacle clearance.', reference: 'ICAO Doc 8168 / AIP ENR 1.5' },
    { question: 'What is the missed approach procedure and when must it be initiated?', options: ['A. Only when directed by ATC', 'B. At DA or MDA if visual reference is not established, or any time a safe landing cannot be assured — the published procedure must be flown', 'C. Optional if the crew believes they can land safely', 'D. Only if the runway is occupied'], correct: 1, explanation: 'Missed approach must be initiated: at DA if visual reference not established (precision), at MDA if visual reference not acquired (non-precision), or any time a safe landing cannot be assured. The published procedure must be flown.', reference: 'ICAO Doc 8168 / AIP ENR 1.5' },
    { question: 'What minimum equipment is required for IFR flight in IMC under CASR?', options: ['A. GPS only is sufficient', 'B. Serviceable attitude indicator, directional indicator, altimeter, VSI, ASI, turn coordinator, approved navigation equipment, two-way radio, and transponder', 'C. Only attitude indicator and altimeter', 'D. No additional requirements beyond VFR'], correct: 1, explanation: 'IFR equipment requirements include all gyroscopic and pressure instruments, approved navigation equipment for the routes/procedures, two-way radio, and transponder. All must be serviceable or deferred per the MEL.', reference: 'CASR Part 91 / CASA IREX Syllabus' },
    { question: 'What is the protected airspace concept for instrument approach procedures?', options: ['A. Airspace where radar coverage is guaranteed', 'B. Obstacle clearance surfaces that guarantee terrain clearance when the procedure is flown correctly within specified tolerances', 'C. Airspace where ATC provides separation', 'D. Area where the ILS signal is protected'], correct: 1, explanation: 'Instrument approach procedures have obstacle clearance surfaces (OCS) that guarantee clearance when the procedure is flown within specified lateral and vertical tolerances. Deviating outside these boundaries removes the obstacle clearance guarantee.', reference: 'ICAO Doc 8168 / CASA IREX Syllabus' },
  ],
}

function findQuestions(subject: string) {
  if (freeQuestions[subject]) return freeQuestions[subject]
  const lower = subject.toLowerCase().trim()
  for (const key of Object.keys(freeQuestions)) {
    if (key.toLowerCase().trim() === lower) return freeQuestions[key]
  }
  for (const key of Object.keys(freeQuestions)) {
    if (lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)) return freeQuestions[key]
  }
  return []
}

function getLicence(subject: string): string {
  if (subject === 'PPL Theory') return 'PPL'
  if (subject === 'Instrument Rating') return 'IREX'
  if (subject === 'Flight Planning') return 'ATPL'
  if (subject === 'Operations, Performance and Planning') return 'CPL'
  return 'CPL'
}

export default function QuizPage({ params }: { params: Promise<{ subject: string }> }) {
  const resolvedParams = use(params)
  const subject = decodeURIComponent(resolvedParams.subject || '')
  const [questions, setQuestions] = useState<any[]>([])
  const [currentIdx, setCurrentIdx] = useState(0)
  const [answered, setAnswered] = useState(false)
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null)
  const [finished, setFinished] = useState(false)
  const [scoreSaved, setScoreSaved] = useState(false)
  const [finalScore, setFinalScore] = useState(0)
  const scoreRef = useRef(0)

  useEffect(() => {
    if (!subject) return
    const bank = findQuestions(subject)
    const shuffled = [...bank].sort(() => Math.random() - 0.5).slice(0, 10)
    setQuestions(shuffled)
    scoreRef.current = 0
  }, [subject])

  async function saveScore(s: number, total: number) {
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return
      const pct = Math.round(s / total * 100)
      const { error } = await supabase.from('scores').insert({
        user_id: user.id,
        subject,
        licence: getLicence(subject),
        score: s,
        total,
        percentage: pct
      })
      if (!error) setScoreSaved(true)
    } catch (e) {
      console.error('Score save error:', e)
    }
  }

  function selectAnswer(idx: number) {
    if (answered) return
    setAnswered(true)
    setSelectedAnswer(idx)
    if (idx === questions[currentIdx].correct) {
      scoreRef.current += 1
    }
  }

  function nextQuestion() {
    const isLast = currentIdx >= questions.length - 1
    if (isLast) {
      const fs = scoreRef.current
      setFinalScore(fs)
      saveScore(fs, questions.length)
      setFinished(true)
    } else {
      setCurrentIdx(i => i + 1)
      setAnswered(false)
      setSelectedAnswer(null)
    }
  }

  function restart() {
    const bank = findQuestions(subject)
    setQuestions([...bank].sort(() => Math.random() - 0.5).slice(0, 10))
    setCurrentIdx(0)
    setFinalScore(0)
    setFinished(false)
    setAnswered(false)
    setSelectedAnswer(null)
    setScoreSaved(false)
    scoreRef.current = 0
  }

  if (!subject || questions.length === 0) return (
    <main style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'system-ui,sans-serif', flexDirection: 'column', gap: '1rem' }}>
      <p style={{ color: '#64748b', fontSize: '16px' }}>Loading questions...</p>
      <a href="/dashboard" style={{ color: '#2563eb', textDecoration: 'none' }}>Back to dashboard</a>
    </main>
  )

  if (finished) {
    const pct = Math.round(finalScore / questions.length * 100)
    return (
      <main style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: 'system-ui,sans-serif', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '2rem' }}>
        <div style={{ background: 'white', borderRadius: '16px', padding: '2.5rem', maxWidth: '500px', width: '100%', border: '1px solid #e2e8f0', textAlign: 'center' }}>
          <div style={{ fontSize: '13px', color: '#94a3b8', fontFamily: 'monospace', marginBottom: '8px' }}>{subject}</div>
          <div style={{ fontSize: '56px', fontWeight: '800', color: '#1e3a6e', fontFamily: 'monospace' }}>{pct}</div>
          <div style={{ fontSize: '16px', color: '#64748b', marginBottom: '8px' }}>percent</div>
          <div style={{ fontSize: '16px', fontWeight: '600', color: pct >= 70 ? '#16a34a' : '#dc2626', marginBottom: '0.5rem' }}>
            {pct >= 70 ? 'Pass — well done!' : 'Below 70% — keep studying'}
          </div>
          {scoreSaved && <div style={{ fontSize: '12px', color: '#10b981', marginBottom: '1.5rem' }}>Score saved to your progress</div>}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginBottom: '2rem' }}>
            <div style={{ background: '#f0fdf4', borderRadius: '8px', padding: '12px' }}>
              <div style={{ fontSize: '24px', fontWeight: '600', color: '#16a34a' }}>{finalScore}</div>
              <div style={{ fontSize: '12px', color: '#64748b' }}>Correct</div>
            </div>
            <div style={{ background: '#fff1f2', borderRadius: '8px', padding: '12px' }}>
              <div style={{ fontSize: '24px', fontWeight: '600', color: '#dc2626' }}>{questions.length - finalScore}</div>
              <div style={{ fontSize: '12px', color: '#64748b' }}>Incorrect</div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button onClick={restart} style={{ flex: 1, background: '#2563eb', color: 'white', border: 'none', borderRadius: '8px', padding: '11px', fontWeight: '600', cursor: 'pointer', fontSize: '14px' }}>Try Again</button>
            <a href="/dashboard" style={{ flex: 1, background: '#f8fafc', color: '#0a1628', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '11px', fontWeight: '600', textDecoration: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '14px' }}>Dashboard</a>
          </div>
          <a href="/progress" style={{ display: 'block', marginTop: '12px', fontSize: '13px', color: '#2563eb', textDecoration: 'none' }}>View all progress →</a>
        </div>
      </main>
    )
  }

  const q = questions[currentIdx]
  const letters = ['A', 'B', 'C', 'D']

  return (
    <main style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: 'system-ui,sans-serif' }}>
      <nav style={{ background: 'white', borderBottom: '1px solid #e2e8f0', padding: '1rem 2rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <span style={{ fontSize: '20px', fontWeight: '800', color: '#2563eb' }}>V1</span>
          <span style={{ fontSize: '20px', fontWeight: '800', color: '#0a1628' }}> Study</span>
        </div>
        <a href="/dashboard" style={{ color: '#64748b', textDecoration: 'none', fontSize: '14px' }}>Back to dashboard</a>
      </nav>
      <div style={{ maxWidth: '700px', margin: '0 auto', padding: '2rem' }}>
        <div style={{ marginBottom: '6px', fontSize: '11px', color: '#94a3b8', fontFamily: 'monospace' }}>Question {currentIdx + 1} of {questions.length}</div>
        <div style={{ background: '#e2e8f0', borderRadius: '99px', height: '4px', marginBottom: '1.5rem', overflow: 'hidden' }}>
          <div style={{ height: '100%', background: '#2563eb', borderRadius: '99px', width: `${(currentIdx / questions.length) * 100}%`, transition: 'width 0.4s' }}></div>
        </div>
        <div style={{ background: 'white', borderRadius: '12px', padding: '1.5rem', border: '1px solid #e2e8f0', marginBottom: '1rem' }}>
          <div style={{ fontSize: '11px', fontWeight: '600', color: '#2563eb', marginBottom: '10px', fontFamily: 'monospace' }}>{subject}</div>
          <div style={{ fontSize: '16px', fontWeight: '600', color: '#0a1628', lineHeight: 1.55, marginBottom: '1.25rem' }}>{q.question}</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {q.options.map((opt: string, i: number) => {
              let bg = 'white'
              let border = '1px solid #e2e8f0'
              let col = '#0a1628'
              if (answered) {
                if (i === q.correct) { bg = '#f0fdf4'; border = '1px solid #16a34a'; col = '#15803d' }
                else if (i === selectedAnswer) { bg = '#fff1f2'; border = '1px solid #dc2626'; col = '#b91c1c' }
                else { col = '#94a3b8' }
              }
              return (
                <button key={i} onClick={() => selectAnswer(i)} disabled={answered} style={{ background: bg, border, borderRadius: '8px', padding: '11px 14px', textAlign: 'left', cursor: answered ? 'default' : 'pointer', fontSize: '14px', color: col, display: 'flex', alignItems: 'flex-start', gap: '10px', width: '100%' }}>
                  <span style={{ fontFamily: 'monospace', fontSize: '12px', background: answered && i === q.correct ? '#dcfce7' : answered && i === selectedAnswer ? '#ffe4e6' : '#f1f5f9', borderRadius: '4px', padding: '1px 6px', minWidth: '22px', textAlign: 'center', flexShrink: 0, marginTop: '1px' }}>
                    {answered && i === q.correct ? '✓' : answered && i === selectedAnswer ? '✗' : letters[i]}
                  </span>
                  <span>{opt.replace(/^[A-D]\.\s*/, '')}</span>
                </button>
              )
            })}
          </div>
        </div>
        {answered && (
          <div style={{ background: '#f0f7ff', border: '1px solid #bfdbfe', borderRadius: '12px', padding: '1.25rem', marginBottom: '1rem' }}>
            <div style={{ fontSize: '13px', fontWeight: '600', color: '#1d4ed8', marginBottom: '8px' }}>Explanation</div>
            <p style={{ fontSize: '13px', lineHeight: 1.65, color: '#1e3a6e', marginBottom: '12px' }}>{q.explanation}</p>
            <div style={{ borderTop: '1px solid #bfdbfe', paddingTop: '10px' }}>
              <div style={{ fontSize: '10px', fontFamily: 'monospace', color: '#2563eb', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Reference</div>
              <div style={{ fontSize: '12px', color: '#3b82f6', fontFamily: 'monospace' }}>{q.reference}</div>
            </div>
          </div>
        )}
        {answered && (
          <button onClick={nextQuestion} style={{ width: '100%', background: '#1e3a6e', color: 'white', border: 'none', borderRadius: '8px', padding: '12px', fontSize: '15px', fontWeight: '600', cursor: 'pointer' }}>
            {currentIdx < questions.length - 1 ? 'Next question →' : 'See results →'}
          </button>
        )}
      </div>
    </main>
  )
}
